language: php

php:
  - 5.6

before_script:
# copy env files
  - cp .env-testing.example .env-testing
# copy codeception files
  - cp codeception.yml.example codeception.yml
  - cp tests/acceptance.suite.yml.example acceptance.suite.yml
  - cp tests/functional.suite.yml.example functional.suite.yml
  - cp tests/unit.suite.yml.example unit.suite.yml
# composer
  - composer self-update
  - composer install --no-interaction
# codeception build
  - ./vendor/bin/codecept build

script:
  - ./vendor/bin/codecept run
